on:
  push:
    branches:
      - master
name: Deploy API
jobs:
  deploy:
    name: Executing remote ssh commands
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Executing remote ssh commands
      uses: AEnterprise/execute-ssh@master
      env:
        DEPLOY_KEY: ${{ secrets.KEY }}
        SERVER_CONNECTION_STRING: ${{ secrets.SERVER_CONNECTION_STRING }}
        COMMAND: "cd ~/Dashboard-api && /usr/bin/git pull && sudo /bin/systemctl restart dashboard.service"
        PORT: ${{ secrets.PORT }}
